(LIT "distutils.command\n\nPackage containing implementation of all the standard Distutils\ncommands.")
(NEWLINE)
(ID "__all__")
(PUNCT "=")
(PUNCT "[")
(LIT "build")
(PUNCT ",")
(LIT "build_py")
(PUNCT ",")
(LIT "build_ext")
(PUNCT ",")
(LIT "build_clib")
(PUNCT ",")
(LIT "build_scripts")
(PUNCT ",")
(LIT "clean")
(PUNCT ",")
(LIT "install")
(PUNCT ",")
(LIT "install_lib")
(PUNCT ",")
(LIT "install_headers")
(PUNCT ",")
(LIT "install_scripts")
(PUNCT ",")
(LIT "install_data")
(PUNCT ",")
(LIT "sdist")
(PUNCT ",")
(LIT "register")
(PUNCT ",")
(LIT "bdist")
(PUNCT ",")
(LIT "bdist_dumb")
(PUNCT ",")
(LIT "bdist_rpm")
(PUNCT ",")
(LIT "bdist_wininst")
(PUNCT ",")
(LIT "check")
(PUNCT ",")
(LIT "upload")
(PUNCT ",")
(PUNCT "]")
(NEWLINE)
(ENDMARKER)
