(LIT "Class representing message/* MIME documents.")
(NEWLINE)
(ID "__all__")
(PUNCT "=")
(PUNCT "[")
(LIT "MIMEMessage")
(PUNCT "]")
(NEWLINE)
(KEYWORD from)
(ID "email")
(KEYWORD import)
(ID "message")
(NEWLINE)
(KEYWORD from)
(ID "email")
(PUNCT ".")
(ID "mime")
(PUNCT ".")
(ID "nonmultipart")
(KEYWORD import)
(ID "MIMENonMultipart")
(NEWLINE)
(KEYWORD class)
(ID "MIMEMessage")
(PUNCT "(")
(ID "MIMENonMultipart")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Class representing message/* MIME documents.")
(NEWLINE)
(KEYWORD def)
(ID "__init__")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "_msg")
(PUNCT ",")
(ID "_subtype")
(PUNCT "=")
(LIT "rfc822")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Create a message/* type MIME document.\n\n        _msg is a message object and must be an instance of Message, or a\n        derived class of Message, otherwise a TypeError is raised.\n\n        Optional _subtype defines the subtype of the contained message.  The\n        default is \"rfc822\" (this is defined by the MIME standard, even though\n        the term \"rfc822\" is technically outdated by RFC 2822).\n        ")
(NEWLINE)
(ID "MIMENonMultipart")
(PUNCT ".")
(ID "__init__")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(LIT "message")
(PUNCT ",")
(ID "_subtype")
(PUNCT ")")
(NEWLINE)
(KEYWORD if)
(KEYWORD not)
(ID "isinstance")
(PUNCT "(")
(ID "_msg")
(PUNCT ",")
(ID "message")
(PUNCT ".")
(ID "Message")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD raise)
(ID "TypeError")
(PUNCT "(")
(LIT "Argument is not an instance of Message")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(ID "message")
(PUNCT ".")
(ID "Message")
(PUNCT ".")
(ID "attach")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "_msg")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "set_default_type")
(PUNCT "(")
(LIT "message/rfc822")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(ENDMARKER)
