(LIT "Encodings and related functions.")
(NEWLINE)
(ID "__all__")
(PUNCT "=")
(PUNCT "[")
(LIT "encode_7or8bit")
(PUNCT ",")
(LIT "encode_base64")
(PUNCT ",")
(LIT "encode_noop")
(PUNCT ",")
(LIT "encode_quopri")
(PUNCT ",")
(PUNCT "]")
(NEWLINE)
(KEYWORD from)
(ID "base64")
(KEYWORD import)
(ID "encodebytes")
(KEYWORD as)
(ID "_bencode")
(NEWLINE)
(KEYWORD from)
(ID "quopri")
(KEYWORD import)
(ID "encodestring")
(KEYWORD as)
(ID "_encodestring")
(NEWLINE)
(KEYWORD def)
(ID "_qencode")
(PUNCT "(")
(ID "s")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "enc")
(PUNCT "=")
(ID "_encodestring")
(PUNCT "(")
(ID "s")
(PUNCT ",")
(ID "quotetabs")
(PUNCT "=")
(KEYWORD True)
(PUNCT ")")
(NEWLINE)
(KEYWORD return)
(ID "enc")
(PUNCT ".")
(ID "replace")
(PUNCT "(")
(LIT #" ")
(PUNCT ",")
(LIT #"=20")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "encode_base64")
(PUNCT "(")
(ID "msg")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Encode the message's payload in Base64.\n\n    Also, add an appropriate Content-Transfer-Encoding header.\n    ")
(NEWLINE)
(ID "orig")
(PUNCT "=")
(ID "msg")
(PUNCT ".")
(ID "get_payload")
(PUNCT "(")
(ID "decode")
(PUNCT "=")
(KEYWORD True)
(PUNCT ")")
(NEWLINE)
(ID "encdata")
(PUNCT "=")
(ID "str")
(PUNCT "(")
(ID "_bencode")
(PUNCT "(")
(ID "orig")
(PUNCT ")")
(PUNCT ",")
(LIT "ascii")
(PUNCT ")")
(NEWLINE)
(ID "msg")
(PUNCT ".")
(ID "set_payload")
(PUNCT "(")
(ID "encdata")
(PUNCT ")")
(NEWLINE)
(ID "msg")
(PUNCT "[")
(LIT "Content-Transfer-Encoding")
(PUNCT "]")
(PUNCT "=")
(LIT "base64")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "encode_quopri")
(PUNCT "(")
(ID "msg")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Encode the message's payload in quoted-printable.\n\n    Also, add an appropriate Content-Transfer-Encoding header.\n    ")
(NEWLINE)
(ID "orig")
(PUNCT "=")
(ID "msg")
(PUNCT ".")
(ID "get_payload")
(PUNCT "(")
(ID "decode")
(PUNCT "=")
(KEYWORD True)
(PUNCT ")")
(NEWLINE)
(ID "encdata")
(PUNCT "=")
(ID "_qencode")
(PUNCT "(")
(ID "orig")
(PUNCT ")")
(NEWLINE)
(ID "msg")
(PUNCT ".")
(ID "set_payload")
(PUNCT "(")
(ID "encdata")
(PUNCT ")")
(NEWLINE)
(ID "msg")
(PUNCT "[")
(LIT "Content-Transfer-Encoding")
(PUNCT "]")
(PUNCT "=")
(LIT "quoted-printable")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "encode_7or8bit")
(PUNCT "(")
(ID "msg")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Set the Content-Transfer-Encoding header to 7bit or 8bit.")
(NEWLINE)
(ID "orig")
(PUNCT "=")
(ID "msg")
(PUNCT ".")
(ID "get_payload")
(PUNCT "(")
(ID "decode")
(PUNCT "=")
(KEYWORD True)
(PUNCT ")")
(NEWLINE)
(KEYWORD if)
(ID "orig")
(KEYWORD is)
(KEYWORD None)
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "msg")
(PUNCT "[")
(LIT "Content-Transfer-Encoding")
(PUNCT "]")
(PUNCT "=")
(LIT "7bit")
(NEWLINE)
(KEYWORD return)
(NEWLINE)
(DEDENT)
(KEYWORD try)
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "orig")
(PUNCT ".")
(ID "decode")
(PUNCT "(")
(LIT "ascii")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD except)
(ID "UnicodeError")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "msg")
(PUNCT "[")
(LIT "Content-Transfer-Encoding")
(PUNCT "]")
(PUNCT "=")
(LIT "8bit")
(NEWLINE)
(DEDENT)
(KEYWORD else)
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "msg")
(PUNCT "[")
(LIT "Content-Transfer-Encoding")
(PUNCT "]")
(PUNCT "=")
(LIT "7bit")
(NEWLINE)
(DEDENT)
(DEDENT)
(KEYWORD def)
(ID "encode_noop")
(PUNCT "(")
(ID "msg")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Do nothing.")
(NEWLINE)
(DEDENT)
(ENDMARKER)
