(LIT "Base class for MIME specializations.")
(NEWLINE)
(ID "__all__")
(PUNCT "=")
(PUNCT "[")
(LIT "MIMEBase")
(PUNCT "]")
(NEWLINE)
(KEYWORD from)
(ID "email")
(KEYWORD import)
(ID "message")
(NEWLINE)
(KEYWORD class)
(ID "MIMEBase")
(PUNCT "(")
(ID "message")
(PUNCT ".")
(ID "Message")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Base class for MIME specializations.")
(NEWLINE)
(KEYWORD def)
(ID "__init__")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "_maintype")
(PUNCT ",")
(ID "_subtype")
(PUNCT ",")
(PUNCT "**")
(ID "_params")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "This constructor adds a Content-Type: and a MIME-Version: header.\n\n        The Content-Type: header is taken from the _maintype and _subtype\n        arguments.  Additional parameters for this header are taken from the\n        keyword arguments.\n        ")
(NEWLINE)
(ID "message")
(PUNCT ".")
(ID "Message")
(PUNCT ".")
(ID "__init__")
(PUNCT "(")
(ID "self")
(PUNCT ")")
(NEWLINE)
(ID "ctype")
(PUNCT "=")
(LIT "%s/%s")
(PUNCT "%")
(PUNCT "(")
(ID "_maintype")
(PUNCT ",")
(ID "_subtype")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "add_header")
(PUNCT "(")
(LIT "Content-Type")
(PUNCT ",")
(ID "ctype")
(PUNCT ",")
(PUNCT "**")
(ID "_params")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT "[")
(LIT "MIME-Version")
(PUNCT "]")
(PUNCT "=")
(LIT "1.0")
(NEWLINE)
(DEDENT)
(DEDENT)
(ENDMARKER)
