(LIT "Class representing image/* type MIME documents.")
(NEWLINE)
(ID "__all__")
(PUNCT "=")
(PUNCT "[")
(LIT "MIMEImage")
(PUNCT "]")
(NEWLINE)
(KEYWORD import)
(ID "imghdr")
(NEWLINE)
(KEYWORD from)
(ID "email")
(KEYWORD import)
(ID "encoders")
(NEWLINE)
(KEYWORD from)
(ID "email")
(PUNCT ".")
(ID "mime")
(PUNCT ".")
(ID "nonmultipart")
(KEYWORD import)
(ID "MIMENonMultipart")
(NEWLINE)
(KEYWORD class)
(ID "MIMEImage")
(PUNCT "(")
(ID "MIMENonMultipart")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Class for generating image/* type MIME documents.")
(NEWLINE)
(KEYWORD def)
(ID "__init__")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "_imagedata")
(PUNCT ",")
(ID "_subtype")
(PUNCT "=")
(KEYWORD None)
(PUNCT ",")
(ID "_encoder")
(PUNCT "=")
(ID "encoders")
(PUNCT ".")
(ID "encode_base64")
(PUNCT ",")
(PUNCT "**")
(ID "_params")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Create an image/* type MIME document.\n\n        _imagedata is a string containing the raw image data.  If this data\n        can be decoded by the standard Python `imghdr' module, then the\n        subtype will be automatically included in the Content-Type header.\n        Otherwise, you can specify the specific image subtype via the _subtype\n        parameter.\n\n        _encoder is a function which will perform the actual encoding for\n        transport of the image data.  It takes one argument, which is this\n        Image instance.  It should use get_payload() and set_payload() to\n        change the payload to the encoded form.  It should also add any\n        Content-Transfer-Encoding or other headers to the message as\n        necessary.  The default encoding is Base64.\n\n        Any additional keyword arguments are passed to the base class\n        constructor, which turns them into parameters on the Content-Type\n        header.\n        ")
(NEWLINE)
(KEYWORD if)
(ID "_subtype")
(KEYWORD is)
(KEYWORD None)
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "_subtype")
(PUNCT "=")
(ID "imghdr")
(PUNCT ".")
(ID "what")
(PUNCT "(")
(KEYWORD None)
(PUNCT ",")
(ID "_imagedata")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD if)
(ID "_subtype")
(KEYWORD is)
(KEYWORD None)
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD raise)
(ID "TypeError")
(PUNCT "(")
(LIT "Could not guess image MIME subtype")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(ID "MIMENonMultipart")
(PUNCT ".")
(ID "__init__")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(LIT "image")
(PUNCT ",")
(ID "_subtype")
(PUNCT ",")
(PUNCT "**")
(ID "_params")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "set_payload")
(PUNCT "(")
(ID "_imagedata")
(PUNCT ")")
(NEWLINE)
(ID "_encoder")
(PUNCT "(")
(ID "self")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(ENDMARKER)
