(LIT "\nIDLE main entry point\n\nRun IDLE as python -m idlelib\n")
(NEWLINE)
(KEYWORD import)
(ID "idlelib")
(PUNCT ".")
(ID "PyShell")
(NEWLINE)
(ID "idlelib")
(PUNCT ".")
(ID "PyShell")
(PUNCT ".")
(ID "main")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(ENDMARKER)
