(LIT "ParenMatch -- An IDLE extension for parenthesis matching.\n\nWhen you hit a right paren, the cursor should move briefly to the left\nparen.  Paren here is used generically; the matching applies to\nparentheses, square brackets, and curly braces.\n")
(NEWLINE)
(KEYWORD from)
(ID "idlelib")
(PUNCT ".")
(ID "HyperParser")
(KEYWORD import)
(ID "HyperParser")
(NEWLINE)
(KEYWORD from)
(ID "idlelib")
(PUNCT ".")
(ID "configHandler")
(KEYWORD import)
(ID "idleConf")
(NEWLINE)
(ID "_openers")
(PUNCT "=")
(PUNCT "{")
(LIT ")")
(PUNCT ":")
(LIT "(")
(PUNCT ",")
(LIT "]")
(PUNCT ":")
(LIT "[")
(PUNCT ",")
(LIT "}")
(PUNCT ":")
(LIT "{")
(PUNCT "}")
(NEWLINE)
(ID "CHECK_DELAY")
(PUNCT "=")
(LIT 100)
(NEWLINE)
(KEYWORD class)
(ID "ParenMatch")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Highlight matching parentheses\n\n    There are three supported style of paren matching, based loosely\n    on the Emacs options.  The style is select based on the\n    HILITE_STYLE attribute; it can be changed used the set_style\n    method.\n\n    The supported styles are:\n\n    default -- When a right paren is typed, highlight the matching\n        left paren for 1/2 sec.\n\n    expression -- When a right paren is typed, highlight the entire\n        expression from the left paren to the right paren.\n\n    TODO:\n        - extend IDLE with configuration dialog to change options\n        - implement rest of Emacs highlight styles (see below)\n        - print mismatch warning in IDLE status window\n\n    Note: In Emacs, there are several styles of highlight where the\n    matching paren is highlighted whenever the cursor is immediately\n    to the right of a right paren.  I don't know how to do that in Tk,\n    so I haven't bothered.\n    ")
(NEWLINE)
(ID "menudefs")
(PUNCT "=")
(PUNCT "[")
(PUNCT "(")
(LIT "edit")
(PUNCT ",")
(PUNCT "[")
(PUNCT "(")
(LIT "Show surrounding parens")
(PUNCT ",")
(LIT "<<flash-paren>>")
(PUNCT ")")
(PUNCT ",")
(PUNCT "]")
(PUNCT ")")
(PUNCT "]")
(NEWLINE)
(ID "STYLE")
(PUNCT "=")
(ID "idleConf")
(PUNCT ".")
(ID "GetOption")
(PUNCT "(")
(LIT "extensions")
(PUNCT ",")
(LIT "ParenMatch")
(PUNCT ",")
(LIT "style")
(PUNCT ",")
(ID "default")
(PUNCT "=")
(LIT "expression")
(PUNCT ")")
(NEWLINE)
(ID "FLASH_DELAY")
(PUNCT "=")
(ID "idleConf")
(PUNCT ".")
(ID "GetOption")
(PUNCT "(")
(LIT "extensions")
(PUNCT ",")
(LIT "ParenMatch")
(PUNCT ",")
(LIT "flash-delay")
(PUNCT ",")
(ID "type")
(PUNCT "=")
(LIT "int")
(PUNCT ",")
(ID "default")
(PUNCT "=")
(LIT 500)
(PUNCT ")")
(NEWLINE)
(ID "HILITE_CONFIG")
(PUNCT "=")
(ID "idleConf")
(PUNCT ".")
(ID "GetHighlight")
(PUNCT "(")
(ID "idleConf")
(PUNCT ".")
(ID "CurrentTheme")
(PUNCT "(")
(PUNCT ")")
(PUNCT ",")
(LIT "hilite")
(PUNCT ")")
(NEWLINE)
(ID "BELL")
(PUNCT "=")
(ID "idleConf")
(PUNCT ".")
(ID "GetOption")
(PUNCT "(")
(LIT "extensions")
(PUNCT ",")
(LIT "ParenMatch")
(PUNCT ",")
(LIT "bell")
(PUNCT ",")
(ID "type")
(PUNCT "=")
(LIT "bool")
(PUNCT ",")
(ID "default")
(PUNCT "=")
(LIT 1)
(PUNCT ")")
(NEWLINE)
(ID "RESTORE_VIRTUAL_EVENT_NAME")
(PUNCT "=")
(LIT "<<parenmatch-check-restore>>")
(NEWLINE)
(ID "RESTORE_SEQUENCES")
(PUNCT "=")
(PUNCT "(")
(LIT "<KeyPress>")
(PUNCT ",")
(LIT "<ButtonPress>")
(PUNCT ",")
(LIT "<Key-Return>")
(PUNCT ",")
(LIT "<Key-BackSpace>")
(PUNCT ")")
(NEWLINE)
(KEYWORD def)
(ID "__init__")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "editwin")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "editwin")
(PUNCT "=")
(ID "editwin")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT "=")
(ID "editwin")
(PUNCT ".")
(ID "text")
(NEWLINE)
(ID "editwin")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "bind")
(PUNCT "(")
(ID "self")
(PUNCT ".")
(ID "RESTORE_VIRTUAL_EVENT_NAME")
(PUNCT ",")
(ID "self")
(PUNCT ".")
(ID "restore_event")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "counter")
(PUNCT "=")
(LIT 0)
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "is_restore_active")
(PUNCT "=")
(LIT 0)
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "set_style")
(PUNCT "(")
(ID "self")
(PUNCT ".")
(ID "STYLE")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "activate_restore")
(PUNCT "(")
(ID "self")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD if)
(KEYWORD not)
(ID "self")
(PUNCT ".")
(ID "is_restore_active")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD for)
(ID "seq")
(KEYWORD in)
(ID "self")
(PUNCT ".")
(ID "RESTORE_SEQUENCES")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "event_add")
(PUNCT "(")
(ID "self")
(PUNCT ".")
(ID "RESTORE_VIRTUAL_EVENT_NAME")
(PUNCT ",")
(ID "seq")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(ID "self")
(PUNCT ".")
(ID "is_restore_active")
(PUNCT "=")
(KEYWORD True)
(NEWLINE)
(DEDENT)
(DEDENT)
(KEYWORD def)
(ID "deactivate_restore")
(PUNCT "(")
(ID "self")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD if)
(ID "self")
(PUNCT ".")
(ID "is_restore_active")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD for)
(ID "seq")
(KEYWORD in)
(ID "self")
(PUNCT ".")
(ID "RESTORE_SEQUENCES")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "event_delete")
(PUNCT "(")
(ID "self")
(PUNCT ".")
(ID "RESTORE_VIRTUAL_EVENT_NAME")
(PUNCT ",")
(ID "seq")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(ID "self")
(PUNCT ".")
(ID "is_restore_active")
(PUNCT "=")
(KEYWORD False)
(NEWLINE)
(DEDENT)
(DEDENT)
(KEYWORD def)
(ID "set_style")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "style")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "STYLE")
(PUNCT "=")
(ID "style")
(NEWLINE)
(KEYWORD if)
(ID "style")
(PUNCT "==")
(LIT "default")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "create_tag")
(PUNCT "=")
(ID "self")
(PUNCT ".")
(ID "create_tag_default")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "set_timeout")
(PUNCT "=")
(ID "self")
(PUNCT ".")
(ID "set_timeout_last")
(NEWLINE)
(DEDENT)
(KEYWORD elif)
(ID "style")
(PUNCT "==")
(LIT "expression")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "create_tag")
(PUNCT "=")
(ID "self")
(PUNCT ".")
(ID "create_tag_expression")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "set_timeout")
(PUNCT "=")
(ID "self")
(PUNCT ".")
(ID "set_timeout_none")
(NEWLINE)
(DEDENT)
(DEDENT)
(KEYWORD def)
(ID "flash_paren_event")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "event")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "indices")
(PUNCT "=")
(PUNCT "(")
(ID "HyperParser")
(PUNCT "(")
(ID "self")
(PUNCT ".")
(ID "editwin")
(PUNCT ",")
(LIT "insert")
(PUNCT ")")
(PUNCT ".")
(ID "get_surrounding_brackets")
(PUNCT "(")
(PUNCT ")")
(PUNCT ")")
(NEWLINE)
(KEYWORD if)
(ID "indices")
(KEYWORD is)
(KEYWORD None)
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "warn_mismatched")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(KEYWORD return)
(NEWLINE)
(DEDENT)
(ID "self")
(PUNCT ".")
(ID "activate_restore")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "create_tag")
(PUNCT "(")
(ID "indices")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "set_timeout_last")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "paren_closed_event")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "event")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "closer")
(PUNCT "=")
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "get")
(PUNCT "(")
(LIT "insert-1c")
(PUNCT ")")
(NEWLINE)
(KEYWORD if)
(ID "closer")
(KEYWORD not)
(KEYWORD in)
(ID "_openers")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD return)
(NEWLINE)
(DEDENT)
(ID "hp")
(PUNCT "=")
(ID "HyperParser")
(PUNCT "(")
(ID "self")
(PUNCT ".")
(ID "editwin")
(PUNCT ",")
(LIT "insert-1c")
(PUNCT ")")
(NEWLINE)
(KEYWORD if)
(KEYWORD not)
(ID "hp")
(PUNCT ".")
(ID "is_in_code")
(PUNCT "(")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD return)
(NEWLINE)
(DEDENT)
(ID "indices")
(PUNCT "=")
(ID "hp")
(PUNCT ".")
(ID "get_surrounding_brackets")
(PUNCT "(")
(ID "_openers")
(PUNCT "[")
(ID "closer")
(PUNCT "]")
(PUNCT ",")
(KEYWORD True)
(PUNCT ")")
(NEWLINE)
(KEYWORD if)
(ID "indices")
(KEYWORD is)
(KEYWORD None)
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "warn_mismatched")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(KEYWORD return)
(NEWLINE)
(DEDENT)
(ID "self")
(PUNCT ".")
(ID "activate_restore")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "create_tag")
(PUNCT "(")
(ID "indices")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "set_timeout")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "restore_event")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "event")
(PUNCT "=")
(KEYWORD None)
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "tag_delete")
(PUNCT "(")
(LIT "paren")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "deactivate_restore")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "counter")
(PUNCT "+=")
(LIT 1)
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "handle_restore_timer")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "timer_count")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD if)
(ID "timer_count")
(PUNCT "==")
(ID "self")
(PUNCT ".")
(ID "counter")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "restore_event")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(KEYWORD def)
(ID "warn_mismatched")
(PUNCT "(")
(ID "self")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD if)
(ID "self")
(PUNCT ".")
(ID "BELL")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "bell")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(KEYWORD def)
(ID "create_tag_default")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "indices")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Highlight the single paren that matches")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "tag_add")
(PUNCT "(")
(LIT "paren")
(PUNCT ",")
(ID "indices")
(PUNCT "[")
(LIT 0)
(PUNCT "]")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "tag_config")
(PUNCT "(")
(LIT "paren")
(PUNCT ",")
(ID "self")
(PUNCT ".")
(ID "HILITE_CONFIG")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "create_tag_expression")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "indices")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Highlight the entire expression")
(NEWLINE)
(KEYWORD if)
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "get")
(PUNCT "(")
(ID "indices")
(PUNCT "[")
(LIT 1)
(PUNCT "]")
(PUNCT ")")
(KEYWORD in)
(PUNCT "(")
(LIT ")")
(PUNCT ",")
(LIT "]")
(PUNCT ",")
(LIT "}")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "rightindex")
(PUNCT "=")
(ID "indices")
(PUNCT "[")
(LIT 1)
(PUNCT "]")
(PUNCT "+")
(LIT "+1c")
(NEWLINE)
(DEDENT)
(KEYWORD else)
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "rightindex")
(PUNCT "=")
(ID "indices")
(PUNCT "[")
(LIT 1)
(PUNCT "]")
(NEWLINE)
(DEDENT)
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "tag_add")
(PUNCT "(")
(LIT "paren")
(PUNCT ",")
(ID "indices")
(PUNCT "[")
(LIT 0)
(PUNCT "]")
(PUNCT ",")
(ID "rightindex")
(PUNCT ")")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "tag_config")
(PUNCT "(")
(LIT "paren")
(PUNCT ",")
(ID "self")
(PUNCT ".")
(ID "HILITE_CONFIG")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "set_timeout_none")
(PUNCT "(")
(ID "self")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Highlight will remain until user input turns it off\n        or the insert has moved")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "counter")
(PUNCT "+=")
(LIT 1)
(NEWLINE)
(KEYWORD def)
(ID "callme")
(PUNCT "(")
(ID "callme")
(PUNCT ",")
(ID "self")
(PUNCT "=")
(ID "self")
(PUNCT ",")
(ID "c")
(PUNCT "=")
(ID "self")
(PUNCT ".")
(ID "counter")
(PUNCT ",")
(ID "index")
(PUNCT "=")
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "index")
(PUNCT "(")
(LIT "insert")
(PUNCT ")")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD if)
(ID "index")
(PUNCT "!=")
(ID "self")
(PUNCT ".")
(ID "text")
(PUNCT ".")
(ID "index")
(PUNCT "(")
(LIT "insert")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "handle_restore_timer")
(PUNCT "(")
(ID "c")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD else)
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "self")
(PUNCT ".")
(ID "editwin")
(PUNCT ".")
(ID "text_frame")
(PUNCT ".")
(ID "after")
(PUNCT "(")
(ID "CHECK_DELAY")
(PUNCT ",")
(ID "callme")
(PUNCT ",")
(ID "callme")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(ID "self")
(PUNCT ".")
(ID "editwin")
(PUNCT ".")
(ID "text_frame")
(PUNCT ".")
(ID "after")
(PUNCT "(")
(ID "CHECK_DELAY")
(PUNCT ",")
(ID "callme")
(PUNCT ",")
(ID "callme")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "set_timeout_last")
(PUNCT "(")
(ID "self")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "The last highlight created will be removed after .5 sec")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "counter")
(PUNCT "+=")
(LIT 1)
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "editwin")
(PUNCT ".")
(ID "text_frame")
(PUNCT ".")
(ID "after")
(PUNCT "(")
(ID "self")
(PUNCT ".")
(ID "FLASH_DELAY")
(PUNCT ",")
(KEYWORD lambda)
(ID "self")
(PUNCT "=")
(ID "self")
(PUNCT ",")
(ID "c")
(PUNCT "=")
(ID "self")
(PUNCT ".")
(ID "counter")
(PUNCT ":")
(ID "self")
(PUNCT ".")
(ID "handle_restore_timer")
(PUNCT "(")
(ID "c")
(PUNCT ")")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(KEYWORD if)
(ID "__name__")
(PUNCT "==")
(LIT "__main__")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD import)
(ID "unittest")
(NEWLINE)
(ID "unittest")
(PUNCT ".")
(ID "main")
(PUNCT "(")
(LIT "idlelib.idle_test.test_parenmatch")
(PUNCT ",")
(ID "verbosity")
(PUNCT "=")
(LIT 2)
(PUNCT ")")
(NEWLINE)
(DEDENT)
(ENDMARKER)
