(LIT "The machinery of importlib: finders, loaders, hooks, etc.")
(NEWLINE)
(KEYWORD import)
(ID "_imp")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "_bootstrap")
(KEYWORD import)
(PUNCT "(")
(ID "SOURCE_SUFFIXES")
(PUNCT ",")
(ID "DEBUG_BYTECODE_SUFFIXES")
(PUNCT ",")
(ID "OPTIMIZED_BYTECODE_SUFFIXES")
(PUNCT ",")
(ID "BYTECODE_SUFFIXES")
(PUNCT ",")
(ID "EXTENSION_SUFFIXES")
(PUNCT ")")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "_bootstrap")
(KEYWORD import)
(ID "ModuleSpec")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "_bootstrap")
(KEYWORD import)
(ID "BuiltinImporter")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "_bootstrap")
(KEYWORD import)
(ID "FrozenImporter")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "_bootstrap")
(KEYWORD import)
(ID "WindowsRegistryFinder")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "_bootstrap")
(KEYWORD import)
(ID "PathFinder")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "_bootstrap")
(KEYWORD import)
(ID "FileFinder")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "_bootstrap")
(KEYWORD import)
(ID "SourceFileLoader")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "_bootstrap")
(KEYWORD import)
(ID "SourcelessFileLoader")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "_bootstrap")
(KEYWORD import)
(ID "ExtensionFileLoader")
(NEWLINE)
(KEYWORD def)
(ID "all_suffixes")
(PUNCT "(")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Returns a list of all recognized module suffixes for this process")
(NEWLINE)
(KEYWORD return)
(ID "SOURCE_SUFFIXES")
(PUNCT "+")
(ID "BYTECODE_SUFFIXES")
(PUNCT "+")
(ID "EXTENSION_SUFFIXES")
(NEWLINE)
(DEDENT)
(ENDMARKER)
