(LIT "Fixer for operator functions.\n\noperator.isCallable(obj)       -> hasattr(obj, '__call__')\noperator.sequenceIncludes(obj) -> operator.contains(obj)\noperator.isSequenceType(obj)   -> isinstance(obj, collections.Sequence)\noperator.isMappingType(obj)    -> isinstance(obj, collections.Mapping)\noperator.isNumberType(obj)     -> isinstance(obj, numbers.Number)\noperator.repeat(obj, n)        -> operator.mul(obj, n)\noperator.irepeat(obj, n)       -> operator.imul(obj, n)\n")
(NEWLINE)
(KEYWORD import)
(ID "collections")
(NEWLINE)
(KEYWORD from)
(ID "lib2to3")
(KEYWORD import)
(ID "fixer_base")
(NEWLINE)
(KEYWORD from)
(ID "lib2to3")
(PUNCT ".")
(ID "fixer_util")
(KEYWORD import)
(ID "Call")
(PUNCT ",")
(ID "Name")
(PUNCT ",")
(ID "String")
(PUNCT ",")
(ID "touch_import")
(NEWLINE)
(KEYWORD def)
(ID "invocation")
(PUNCT "(")
(ID "s")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD def)
(ID "dec")
(PUNCT "(")
(ID "f")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "f")
(PUNCT ".")
(ID "invocation")
(PUNCT "=")
(ID "s")
(NEWLINE)
(KEYWORD return)
(ID "f")
(NEWLINE)
(DEDENT)
(KEYWORD return)
(ID "dec")
(NEWLINE)
(DEDENT)
(KEYWORD class)
(ID "FixOperator")
(PUNCT "(")
(ID "fixer_base")
(PUNCT ".")
(ID "BaseFix")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "BM_compatible")
(PUNCT "=")
(KEYWORD True)
(NEWLINE)
(ID "order")
(PUNCT "=")
(LIT "pre")
(NEWLINE)
(ID "methods")
(PUNCT "=")
(LIT "\n              method=('isCallable'|'sequenceIncludes'\n                     |'isSequenceType'|'isMappingType'|'isNumberType'\n                     |'repeat'|'irepeat')\n              ")
(NEWLINE)
(ID "obj")
(PUNCT "=")
(LIT "'(' obj=any ')'")
(NEWLINE)
(ID "PATTERN")
(PUNCT "=")
(LIT "\n              power< module='operator'\n                trailer< '.' %(methods)s > trailer< %(obj)s > >\n              |\n              power< %(methods)s trailer< %(obj)s > >\n              ")
(PUNCT "%")
(ID "dict")
(PUNCT "(")
(ID "methods")
(PUNCT "=")
(ID "methods")
(PUNCT ",")
(ID "obj")
(PUNCT "=")
(ID "obj")
(PUNCT ")")
(NEWLINE)
(KEYWORD def)
(ID "transform")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "method")
(PUNCT "=")
(ID "self")
(PUNCT ".")
(ID "_check_method")
(PUNCT "(")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(NEWLINE)
(KEYWORD if)
(ID "method")
(KEYWORD is)
(KEYWORD not)
(KEYWORD None)
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD return)
(ID "method")
(PUNCT "(")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(PUNCT "@")
(ID "invocation")
(PUNCT "(")
(LIT "operator.contains(%s)")
(PUNCT ")")
(NEWLINE)
(KEYWORD def)
(ID "_sequenceIncludes")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD return)
(ID "self")
(PUNCT ".")
(ID "_handle_rename")
(PUNCT "(")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ",")
(LIT "contains")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(PUNCT "@")
(ID "invocation")
(PUNCT "(")
(LIT "hasattr(%s, '__call__')")
(PUNCT ")")
(NEWLINE)
(KEYWORD def)
(ID "_isCallable")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "obj")
(PUNCT "=")
(ID "results")
(PUNCT "[")
(LIT "obj")
(PUNCT "]")
(NEWLINE)
(ID "args")
(PUNCT "=")
(PUNCT "[")
(ID "obj")
(PUNCT ".")
(ID "clone")
(PUNCT "(")
(PUNCT ")")
(PUNCT ",")
(ID "String")
(PUNCT "(")
(LIT ", ")
(PUNCT ")")
(PUNCT ",")
(ID "String")
(PUNCT "(")
(LIT "'__call__'")
(PUNCT ")")
(PUNCT "]")
(NEWLINE)
(KEYWORD return)
(ID "Call")
(PUNCT "(")
(ID "Name")
(PUNCT "(")
(LIT "hasattr")
(PUNCT ")")
(PUNCT ",")
(ID "args")
(PUNCT ",")
(ID "prefix")
(PUNCT "=")
(ID "node")
(PUNCT ".")
(ID "prefix")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(PUNCT "@")
(ID "invocation")
(PUNCT "(")
(LIT "operator.mul(%s)")
(PUNCT ")")
(NEWLINE)
(KEYWORD def)
(ID "_repeat")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD return)
(ID "self")
(PUNCT ".")
(ID "_handle_rename")
(PUNCT "(")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ",")
(LIT "mul")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(PUNCT "@")
(ID "invocation")
(PUNCT "(")
(LIT "operator.imul(%s)")
(PUNCT ")")
(NEWLINE)
(KEYWORD def)
(ID "_irepeat")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD return)
(ID "self")
(PUNCT ".")
(ID "_handle_rename")
(PUNCT "(")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ",")
(LIT "imul")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(PUNCT "@")
(ID "invocation")
(PUNCT "(")
(LIT "isinstance(%s, collections.Sequence)")
(PUNCT ")")
(NEWLINE)
(KEYWORD def)
(ID "_isSequenceType")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD return)
(ID "self")
(PUNCT ".")
(ID "_handle_type2abc")
(PUNCT "(")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ",")
(LIT "collections")
(PUNCT ",")
(LIT "Sequence")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(PUNCT "@")
(ID "invocation")
(PUNCT "(")
(LIT "isinstance(%s, collections.Mapping)")
(PUNCT ")")
(NEWLINE)
(KEYWORD def)
(ID "_isMappingType")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD return)
(ID "self")
(PUNCT ".")
(ID "_handle_type2abc")
(PUNCT "(")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ",")
(LIT "collections")
(PUNCT ",")
(LIT "Mapping")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(PUNCT "@")
(ID "invocation")
(PUNCT "(")
(LIT "isinstance(%s, numbers.Number)")
(PUNCT ")")
(NEWLINE)
(KEYWORD def)
(ID "_isNumberType")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD return)
(ID "self")
(PUNCT ".")
(ID "_handle_type2abc")
(PUNCT "(")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ",")
(LIT "numbers")
(PUNCT ",")
(LIT "Number")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "_handle_rename")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ",")
(ID "name")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "method")
(PUNCT "=")
(ID "results")
(PUNCT "[")
(LIT "method")
(PUNCT "]")
(PUNCT "[")
(LIT 0)
(PUNCT "]")
(NEWLINE)
(ID "method")
(PUNCT ".")
(ID "value")
(PUNCT "=")
(ID "name")
(NEWLINE)
(ID "method")
(PUNCT ".")
(ID "changed")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "_handle_type2abc")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ",")
(ID "module")
(PUNCT ",")
(ID "abc")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "touch_import")
(PUNCT "(")
(KEYWORD None)
(PUNCT ",")
(ID "module")
(PUNCT ",")
(ID "node")
(PUNCT ")")
(NEWLINE)
(ID "obj")
(PUNCT "=")
(ID "results")
(PUNCT "[")
(LIT "obj")
(PUNCT "]")
(NEWLINE)
(ID "args")
(PUNCT "=")
(PUNCT "[")
(ID "obj")
(PUNCT ".")
(ID "clone")
(PUNCT "(")
(PUNCT ")")
(PUNCT ",")
(ID "String")
(PUNCT "(")
(LIT ", ")
(PUNCT "+")
(LIT ".")
(PUNCT ".")
(ID "join")
(PUNCT "(")
(PUNCT "[")
(ID "module")
(PUNCT ",")
(ID "abc")
(PUNCT "]")
(PUNCT ")")
(PUNCT ")")
(PUNCT "]")
(NEWLINE)
(KEYWORD return)
(ID "Call")
(PUNCT "(")
(ID "Name")
(PUNCT "(")
(LIT "isinstance")
(PUNCT ")")
(PUNCT ",")
(ID "args")
(PUNCT ",")
(ID "prefix")
(PUNCT "=")
(ID "node")
(PUNCT ".")
(ID "prefix")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(KEYWORD def)
(ID "_check_method")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "method")
(PUNCT "=")
(ID "getattr")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(LIT "_")
(PUNCT "+")
(ID "results")
(PUNCT "[")
(LIT "method")
(PUNCT "]")
(PUNCT "[")
(LIT 0)
(PUNCT "]")
(PUNCT ".")
(ID "value")
(PUNCT ")")
(NEWLINE)
(KEYWORD if)
(ID "isinstance")
(PUNCT "(")
(ID "method")
(PUNCT ",")
(ID "collections")
(PUNCT ".")
(ID "Callable")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD if)
(LIT "module")
(KEYWORD in)
(ID "results")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD return)
(ID "method")
(NEWLINE)
(DEDENT)
(KEYWORD else)
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "sub")
(PUNCT "=")
(PUNCT "(")
(ID "str")
(PUNCT "(")
(ID "results")
(PUNCT "[")
(LIT "obj")
(PUNCT "]")
(PUNCT ")")
(PUNCT ",")
(PUNCT ")")
(NEWLINE)
(ID "invocation_str")
(PUNCT "=")
(ID "method")
(PUNCT ".")
(ID "invocation")
(PUNCT "%")
(ID "sub")
(NEWLINE)
(ID "self")
(PUNCT ".")
(ID "warning")
(PUNCT "(")
(ID "node")
(PUNCT ",")
(LIT "You should use '%s' here.")
(PUNCT "%")
(ID "invocation_str")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(KEYWORD return)
(KEYWORD None)
(NEWLINE)
(DEDENT)
(DEDENT)
(ENDMARKER)
