(LIT "Export the Python grammar and symbols.")
(NEWLINE)
(KEYWORD import)
(ID "os")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "pgen2")
(KEYWORD import)
(ID "token")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "pgen2")
(KEYWORD import)
(ID "driver")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(KEYWORD import)
(ID "pytree")
(NEWLINE)
(ID "_GRAMMAR_FILE")
(PUNCT "=")
(ID "os")
(PUNCT ".")
(ID "path")
(PUNCT ".")
(ID "join")
(PUNCT "(")
(ID "os")
(PUNCT ".")
(ID "path")
(PUNCT ".")
(ID "dirname")
(PUNCT "(")
(ID "__file__")
(PUNCT ")")
(PUNCT ",")
(LIT "Grammar.txt")
(PUNCT ")")
(NEWLINE)
(ID "_PATTERN_GRAMMAR_FILE")
(PUNCT "=")
(ID "os")
(PUNCT ".")
(ID "path")
(PUNCT ".")
(ID "join")
(PUNCT "(")
(ID "os")
(PUNCT ".")
(ID "path")
(PUNCT ".")
(ID "dirname")
(PUNCT "(")
(ID "__file__")
(PUNCT ")")
(PUNCT ",")
(LIT "PatternGrammar.txt")
(PUNCT ")")
(NEWLINE)
(KEYWORD class)
(ID "Symbols")
(PUNCT "(")
(ID "object")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(KEYWORD def)
(ID "__init__")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "grammar")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(LIT "Initializer.\n\n        Creates an attribute for each grammar symbol (nonterminal),\n        whose value is the symbol's type (an int >= 256).\n        ")
(NEWLINE)
(KEYWORD for)
(ID "name")
(PUNCT ",")
(ID "symbol")
(KEYWORD in)
(ID "grammar")
(PUNCT ".")
(ID "symbol2number")
(PUNCT ".")
(ID "items")
(PUNCT "(")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "setattr")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "name")
(PUNCT ",")
(ID "symbol")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(DEDENT)
(ID "python_grammar")
(PUNCT "=")
(ID "driver")
(PUNCT ".")
(ID "load_grammar")
(PUNCT "(")
(ID "_GRAMMAR_FILE")
(PUNCT ")")
(NEWLINE)
(ID "python_symbols")
(PUNCT "=")
(ID "Symbols")
(PUNCT "(")
(ID "python_grammar")
(PUNCT ")")
(NEWLINE)
(ID "python_grammar_no_print_statement")
(PUNCT "=")
(ID "python_grammar")
(PUNCT ".")
(ID "copy")
(PUNCT "(")
(PUNCT ")")
(NEWLINE)
(KEYWORD del)
(ID "python_grammar_no_print_statement")
(PUNCT ".")
(ID "keywords")
(PUNCT "[")
(LIT "print")
(PUNCT "]")
(NEWLINE)
(ID "pattern_grammar")
(PUNCT "=")
(ID "driver")
(PUNCT ".")
(ID "load_grammar")
(PUNCT "(")
(ID "_PATTERN_GRAMMAR_FILE")
(PUNCT ")")
(NEWLINE)
(ID "pattern_symbols")
(PUNCT "=")
(ID "Symbols")
(PUNCT "(")
(ID "pattern_grammar")
(PUNCT ")")
(NEWLINE)
(ENDMARKER)
