(LIT "Fixer that replaces deprecated unittest method names.")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(PUNCT ".")
(ID "fixer_base")
(KEYWORD import)
(ID "BaseFix")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(PUNCT ".")
(ID "fixer_util")
(KEYWORD import)
(ID "Name")
(NEWLINE)
(ID "NAMES")
(PUNCT "=")
(ID "dict")
(PUNCT "(")
(ID "assert_")
(PUNCT "=")
(LIT "assertTrue")
(PUNCT ",")
(ID "assertEquals")
(PUNCT "=")
(LIT "assertEqual")
(PUNCT ",")
(ID "assertNotEquals")
(PUNCT "=")
(LIT "assertNotEqual")
(PUNCT ",")
(ID "assertAlmostEquals")
(PUNCT "=")
(LIT "assertAlmostEqual")
(PUNCT ",")
(ID "assertNotAlmostEquals")
(PUNCT "=")
(LIT "assertNotAlmostEqual")
(PUNCT ",")
(ID "assertRegexpMatches")
(PUNCT "=")
(LIT "assertRegex")
(PUNCT ",")
(ID "assertRaisesRegexp")
(PUNCT "=")
(LIT "assertRaisesRegex")
(PUNCT ",")
(ID "failUnlessEqual")
(PUNCT "=")
(LIT "assertEqual")
(PUNCT ",")
(ID "failIfEqual")
(PUNCT "=")
(LIT "assertNotEqual")
(PUNCT ",")
(ID "failUnlessAlmostEqual")
(PUNCT "=")
(LIT "assertAlmostEqual")
(PUNCT ",")
(ID "failIfAlmostEqual")
(PUNCT "=")
(LIT "assertNotAlmostEqual")
(PUNCT ",")
(ID "failUnless")
(PUNCT "=")
(LIT "assertTrue")
(PUNCT ",")
(ID "failUnlessRaises")
(PUNCT "=")
(LIT "assertRaises")
(PUNCT ",")
(ID "failIf")
(PUNCT "=")
(LIT "assertFalse")
(PUNCT ",")
(PUNCT ")")
(NEWLINE)
(KEYWORD class)
(ID "FixAsserts")
(PUNCT "(")
(ID "BaseFix")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "PATTERN")
(PUNCT "=")
(LIT "\n              power< any+ trailer< '.' meth=(%s)> any* >\n              ")
(PUNCT "%")
(LIT "|")
(PUNCT ".")
(ID "join")
(PUNCT "(")
(ID "map")
(PUNCT "(")
(ID "repr")
(PUNCT ",")
(ID "NAMES")
(PUNCT ")")
(PUNCT ")")
(NEWLINE)
(KEYWORD def)
(ID "transform")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "name")
(PUNCT "=")
(ID "results")
(PUNCT "[")
(LIT "meth")
(PUNCT "]")
(PUNCT "[")
(LIT 0)
(PUNCT "]")
(NEWLINE)
(ID "name")
(PUNCT ".")
(ID "replace")
(PUNCT "(")
(ID "Name")
(PUNCT "(")
(ID "NAMES")
(PUNCT "[")
(ID "str")
(PUNCT "(")
(ID "name")
(PUNCT ")")
(PUNCT "]")
(PUNCT ",")
(ID "prefix")
(PUNCT "=")
(ID "name")
(PUNCT ".")
(ID "prefix")
(PUNCT ")")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(ENDMARKER)
