(LIT "Fix bound method attributes (method.im_? -> method.__?__).\n")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(PUNCT ".")
(KEYWORD import)
(ID "fixer_base")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(PUNCT ".")
(ID "fixer_util")
(KEYWORD import)
(ID "Name")
(NEWLINE)
(ID "MAP")
(PUNCT "=")
(PUNCT "{")
(LIT "im_func")
(PUNCT ":")
(LIT "__func__")
(PUNCT ",")
(LIT "im_self")
(PUNCT ":")
(LIT "__self__")
(PUNCT ",")
(LIT "im_class")
(PUNCT ":")
(LIT "__self__.__class__")
(PUNCT "}")
(NEWLINE)
(KEYWORD class)
(ID "FixMethodattrs")
(PUNCT "(")
(ID "fixer_base")
(PUNCT ".")
(ID "BaseFix")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "BM_compatible")
(PUNCT "=")
(KEYWORD True)
(NEWLINE)
(ID "PATTERN")
(PUNCT "=")
(LIT "\n    power< any+ trailer< '.' attr=('im_func' | 'im_self' | 'im_class') > any* >\n    ")
(NEWLINE)
(KEYWORD def)
(ID "transform")
(PUNCT "(")
(ID "self")
(PUNCT ",")
(ID "node")
(PUNCT ",")
(ID "results")
(PUNCT ")")
(PUNCT ":")
(NEWLINE)
(INDENT)
(ID "attr")
(PUNCT "=")
(ID "results")
(PUNCT "[")
(LIT "attr")
(PUNCT "]")
(PUNCT "[")
(LIT 0)
(PUNCT "]")
(NEWLINE)
(ID "new")
(PUNCT "=")
(ID "MAP")
(PUNCT "[")
(ID "attr")
(PUNCT ".")
(ID "value")
(PUNCT "]")
(NEWLINE)
(ID "attr")
(PUNCT ".")
(ID "replace")
(PUNCT "(")
(ID "Name")
(PUNCT "(")
(ID "new")
(PUNCT ",")
(ID "prefix")
(PUNCT "=")
(ID "attr")
(PUNCT ".")
(ID "prefix")
(PUNCT ")")
(PUNCT ")")
(NEWLINE)
(DEDENT)
(DEDENT)
(ENDMARKER)
