(LIT "\nPython unit testing framework, based on Erich Gamma's JUnit and Kent Beck's\nSmalltalk testing framework.\n\nThis module contains the core framework classes that form the basis of\nspecific test cases and suites (TestCase, TestSuite etc.), and also a\ntext-based utility class for running the tests and reporting the results\n (TextTestRunner).\n\nSimple usage:\n\n    import unittest\n\n    class IntegerArithmeticTestCase(unittest.TestCase):\n        def testAdd(self):  ## test method names begin 'test*'\n            self.assertEqual((1 + 2), 3)\n            self.assertEqual(0 + 1, 1)\n        def testMultiply(self):\n            self.assertEqual((0 * 10), 0)\n            self.assertEqual((5 * 8), 40)\n\n    if __name__ == '__main__':\n        unittest.main()\n\nFurther information is available in the bundled documentation, and from\n\n  http://docs.python.org/library/unittest.html\n\nCopyright (c) 1999-2003 Steve Purcell\nCopyright (c) 2003-2010 Python Software Foundation\nThis module is free software, and you may redistribute it and/or modify\nit under the same terms as Python itself, so long as this copyright message\nand disclaimer are retained in their original form.\n\nIN NO EVENT SHALL THE AUTHOR BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT,\nSPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OF\nTHIS CODE, EVEN IF THE AUTHOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH\nDAMAGE.\n\nTHE AUTHOR SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT\nLIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\nPARTICULAR PURPOSE.  THE CODE PROVIDED HEREUNDER IS ON AN \"AS IS\" BASIS,\nAND THERE IS NO OBLIGATION WHATSOEVER TO PROVIDE MAINTENANCE,\nSUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.\n")
(NEWLINE)
(ID "__all__")
(PUNCT "=")
(PUNCT "[")
(LIT "TestResult")
(PUNCT ",")
(LIT "TestCase")
(PUNCT ",")
(LIT "TestSuite")
(PUNCT ",")
(LIT "TextTestRunner")
(PUNCT ",")
(LIT "TestLoader")
(PUNCT ",")
(LIT "FunctionTestCase")
(PUNCT ",")
(LIT "main")
(PUNCT ",")
(LIT "defaultTestLoader")
(PUNCT ",")
(LIT "SkipTest")
(PUNCT ",")
(LIT "skip")
(PUNCT ",")
(LIT "skipIf")
(PUNCT ",")
(LIT "skipUnless")
(PUNCT ",")
(LIT "expectedFailure")
(PUNCT ",")
(LIT "TextTestResult")
(PUNCT ",")
(LIT "installHandler")
(PUNCT ",")
(LIT "registerResult")
(PUNCT ",")
(LIT "removeResult")
(PUNCT ",")
(LIT "removeHandler")
(PUNCT "]")
(NEWLINE)
(ID "__all__")
(PUNCT ".")
(ID "extend")
(PUNCT "(")
(PUNCT "[")
(LIT "getTestCaseNames")
(PUNCT ",")
(LIT "makeSuite")
(PUNCT ",")
(LIT "findTestCases")
(PUNCT "]")
(PUNCT ")")
(NEWLINE)
(ID "__unittest")
(PUNCT "=")
(KEYWORD True)
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "result")
(KEYWORD import)
(ID "TestResult")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "case")
(KEYWORD import)
(PUNCT "(")
(ID "TestCase")
(PUNCT ",")
(ID "FunctionTestCase")
(PUNCT ",")
(ID "SkipTest")
(PUNCT ",")
(ID "skip")
(PUNCT ",")
(ID "skipIf")
(PUNCT ",")
(ID "skipUnless")
(PUNCT ",")
(ID "expectedFailure")
(PUNCT ")")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "suite")
(KEYWORD import)
(ID "BaseTestSuite")
(PUNCT ",")
(ID "TestSuite")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "loader")
(KEYWORD import)
(PUNCT "(")
(ID "TestLoader")
(PUNCT ",")
(ID "defaultTestLoader")
(PUNCT ",")
(ID "makeSuite")
(PUNCT ",")
(ID "getTestCaseNames")
(PUNCT ",")
(ID "findTestCases")
(PUNCT ")")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "main")
(KEYWORD import)
(ID "TestProgram")
(PUNCT ",")
(ID "main")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "runner")
(KEYWORD import)
(ID "TextTestRunner")
(PUNCT ",")
(ID "TextTestResult")
(NEWLINE)
(KEYWORD from)
(PUNCT ".")
(ID "signals")
(KEYWORD import)
(ID "installHandler")
(PUNCT ",")
(ID "registerResult")
(PUNCT ",")
(ID "removeResult")
(PUNCT ",")
(ID "removeHandler")
(NEWLINE)
(ID "_TextTestResult")
(PUNCT "=")
(ID "TextTestResult")
(NEWLINE)
(ENDMARKER)
